### ISSUE TITLE
Reproducing M5 (Walmart) results from paper

### ISSUE THREAD

**Issue by calvinmccarter** [blei-lab/treeffuser#101]
Thanks for providing usable software, and for the notebooks you provided. I'm trying to replicate your M5 (Walmart) experiments , and am having difficulty. I do see the following (see [gist](https://gist.github.com/calvinmccarter/07afe42774e3b793b8589e1884d8d323)):

> Model Treeffuser has a CRPS of {'crps_100': 0.6448642942915247}

Does this correspond to the reported Treeffuser CRPS of 6.44 in Table 2?

**Comment by ANazaret** [comment]
Hello @calvinmccarter, thank you for your question.

Yes you are exactly right! For all experiments, we factorized the power of tens out of the metrics for readability between rows (0.644 --> 6.44).
We have edited the paper tables to make that clearer:

<img width="570" alt="image" src="https://github.com/user-attachments/assets/b3dc52ae-236b-4b42-9ca4-dc3deab35376">

Let us know if we can help with anything else!

**Comment by calvinmccarter** [comment]
Thanks so much for the help @ANazaret ! I'm now trying to replicate the "Treeffuser (no tuning)" result (see my new [gist](https://gist.github.com/calvinmccarter/2cce9f6d06adbd48efebf32d788c84b9)). I'm getting an even better CRPS ({'crps_100': 0.6524468580538034}), the same MAE ('mae': 0.9883351454782684), but worse RMSE ('rmse': 2.1792834439725737). In case this helps with the discrepancy, in cell 25 of this gist, I'm using the following hyperparams, based on Appendix C:

> {"n_estimators": 3000, "learning_rate": 0.1, "num_leaves": 32, "early_stopping_rounds": 50, "n_repeats": 10}

**Comment by aagrande** [comment]
Thank you for your question, @calvinmccarter!

It looks like the hyperparameters that we used for Treeffuser (no tuning) weren't updated in the paper. You can find the correct hyperparameters under [testbed/src/testbed/models/treeffuser.py](https://github.com/blei-lab/treeffuser/blob/main/testbed/src/testbed/models/treeffuser.py):

> {"n_estimators": 3000, "learning_rate": 0.1, "num_leaves": 31, "early_stopping_rounds": 50, "n_repeats": 30}

We've updated the paper to reflect this—thanks for helping us catch the typo!

**Comment by calvinmccarter** [comment]
Thanks for looking into this, @aagrande -- mystery resolved!
