### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by freedom-cx** [blei-lab/treeffuser#104]
![微信图片_20241013114800](https://github.com/user-attachments/assets/ef3f5894-733d-42d7-bc4e-a25448189e82)

**Comment by velezbeltran** [comment]
Hello @freedom-cx ! Thank you for your interest in using Treeffuser. Based on the error message, it appears that your Python version is too old to support our package. Treeffuser requires Python 3.9 or above.

What version would you like support for? Is there a particular application you’re working with that requires an older Python version? If not, consider upgrading to a newer version. Here’s a [tutorial on upgrading Python](https://4geeks.com/how-to/how-to-update-python-version). Let me know if you need any help!

**Comment by freedom-cx** [comment]
> 您好 ！感谢您对使用 Treeffuser 的兴趣。根据错误消息，您的 Python 版本似乎太旧，无法支持我们的软件包。Treeffuser 需要 Python 3.9 或更高版本。
> 
> 您希望支持哪个版本？（您可以用来检查）您正在使用的特定应用程序是否需要较旧的 Python 版本？如果没有，请考虑升级到较新的版本。这是[关于升级 Python 的教程](https://4geeks.com/how-to/how-to-update-python-version)。如果您需要任何帮助，请告诉我！`python --version`

Thanks for your reply. Following your solution I solved my problem.

**Comment by velezbeltran** [comment]
Great to hear!
